### ISSUE TITLE
quick question on pre-fetching from jwks url

### ISSUE THREAD

**Issue by reverendpaco** [joken-elixir/joken_jwks#15]
I have integrated jwks in to my application and it works quite nicely, however I notice that it does not fetch against the jwks url until the first attempt, so each time I reboot my server, I have to log in once (which does not validate) at which point I see joken/jwks go and fetch the keys and then all subsequent logins work.  I have tried variations of the init options (should_start and first_fetch_sync) but they do nothing.  

I suppose I could start a Task at application startup to verify a well-known token to jumpstart the process, but was wondering if I was missing something obvious.

thanks

**Comment by victorolinasc** [comment]
Hi @reverendpaco ! 

There are some initialization options for the default strategy (which I assume you are using). They _should_ do what you want here and I am one user of them. I had no problems with fetching first sync.

The option `should_start` is meant to be used for testing environments.

What I'd advice you is to enable logging with log_level :debug and see if it spits logs during your app boot.

Otherwise we should check your OTP supervision tree to be sure the strategy was started properly.

Hope it helps!

**Comment by reverendpaco** [comment]
@victorolinasc   which option explicitly in the init()?

My app startup has the default strategy + a time interval (as suggested in the docs) which gets passed into the init which does keyword the merges.  So I think I'm following all the right notions.  

An interesting thing that does occur during startup (when I had debug level at DEBUG) was the appearance of  excessive failures of CA certificates from HTTPotion:
`[info] TLS :client: In state :certify at ssl_handshake.erl:1772 generated CLIENT ALERT: Fatal - Unknown CA
`
There are hundreds of these until the moment I first log in.  I know erlang and TLS is kinda wonky, but it is odd that the first log in makes the issue disappear.  Maybe the first sync runs a slightly different set of options to the jwks url?   

FWIW,  the JWKS site I am hitting is my own, and this might be a problem (as I know the SSL certificate is not wildcard and could freak out a client like HTTPotion).   I didn't want to be dependent on an okta or a cognito for initial development, so I pried the "n" and "e" modulus and exponent out of the jose jwks token and exposed it from one app (my stubbed IdP) so that another app can use joken-jwks.  But this, again, would be odd as I can see joken-jwks run the fetch work (but only after I try to log in for the first time).   Again, maybe the pre-fetch runs a slightly different set of http-options?  I'll dig into the code to see what I can see.

**Comment by victorolinasc** [comment]
This is very strange behaviour indeed. Joken JWKS uses the same client for fetching the first and all other tries.

Perhaps your application is overriding the tesla adapter configuration? The code is here: https://github.com/joken-elixir/joken_jwks/blob/master/lib/joken_jwks/http_fetcher.ex

It uses this to fetch the Tesla client (which I believe you've configured to accept a self-signed certificate):

```elixir
 adapter =
      Application.get_env(:tesla, __MODULE__)[:adapter] ||
        Application.get_env(:tesla, :adapter, @default_adapter)

    adapter = opts[:http_adapter] || adapter
```

This is trying to get:
- first the `config :tesla, JokenJwks.HttpFetcher, adapter: xxxxx
- then `:tesla, :adapter, xxxxxx`
- then `@default_adapter` which is `Tesla.Adapter.Hackney` and its default configuration (which validates the certificate)
- then `:http_adapter` key in opts for its init call

Perhaps you using `@default_adapter` which validates all certificate chain and setting a default adapter later?

If all else fails, then I'd be glad if you could provide a project that reproduces the issue so that I can take a look. You can also debug the library call to show more logging information.

**Comment by reverendpaco** [comment]
Apologies for the delay and lack of response.  I am almost certain the issue has to do with the 'rogue' SSL certificate I was using, but find no need to try to resolve it.   In the past week I pointed the jwks url to the Cognito jwks, instead of my mock URL, and the issue disappeared.  I have left a note for myself and internal developers to be aware of the issue for startup **if** we use our internal mocking server, but don't have the time to put together a deeper dive. 

Thank you for your responses though, and thank you for the OSS.  We have greatly benefited from it.

**Comment by victorolinasc** [comment]
I am glad it worked with a public valid SSL! Also glad that this is helping you in some manner!

I'll close this now. Feel free to re-open if the issue reappears.

Stay safe!
