### ISSUE TITLE
Question about manually refetch the token from public API (e.g. google).

### ISSUE THREAD

**Issue by isavita** [joken-elixir/joken_jwks#30]
Thank you, for the very nice library!
I have one question for **sync retrying** logic.
Is it possible synchronously to refetch the public_key on error?
For example, 
1) There is request with **JWT TOKEN**  generated with the **new public key** (e.g. with `google public key`).
2) On validation of the **JWT TOKEN** with `GoogleToken.verify_and_validate(token)` there is error for the token.
3) What kind of error will get one **(2)**? How could I refetch sync the token and retry manually on point **(2)**?
At the moment if I understand correctly the flow, the new token will be refetch base on how often the **time_interval** and  all request meanwhile with the new token will be failing.

**Comment by isavita** [comment]
For the moment I rewrite the `poll` function to allow manually to send message for refetch. 
```elixir
def poll(opts) do
  interval = opts[:time_interval]

  receive do
    :clean_cache_and_refetch ->
      EtsCache.set_status(:refresh)
      _ = check_fetch(opts)
      poll(opts)
  after
    interval ->
      _ = check_fetch(opts)
      poll(opts)
  end
end
```
I am not sure if there is no better way of doing that.

**Comment by lovebes** [comment]
Question: how were you able to redefine `poll()` only from the `JokenJwks.DefaultStrategyTemplate`?
Or did you copy the entire code from `JokenJwks.DefaultStrategyTemplate` to create the changes?

Your needs are more aligned with a GenServer. That way, you don't need to go too "raw" and use `send()`.
It would be a cleaner approach to do `MyApp.MyStrategy.clean_cache_and_refetch()`.

That way, code is abstracted and nested inside `MyApp.MyStrategy`, and inner workings are not exposed.

This way you can use a better polling strategy by using GenServer, instead of doing Task-based polling. This is what I need to do after finding a case where Task-based polling fails and keeps restarting, ultimately failing the Supervisor.

**Comment by victorolinasc** [comment]
@isavita currently there is no sync way of retrying the request manually. 

It is important to note that many times this code is executed in a request process. If you don't lock the re-fetching it will probably make many requests until you can sync it locally. 

As @lovebes has advised, your use case is different than the current default strategy here. You can implement your own strategy but I will try to add more robust options and scalability to the default approach too.

@lovebes has even proposed PRs that I am taking way too long to merge. I will try to do it ASAP.

**Comment by victorolinasc** [comment]
Either way, there is no manual to re-fetch currently so I will close this for now.
