### ISSUE TITLE
Add example for multiple JWKS url's

### ISSUE THREAD

**Issue by jrissler** [joken-elixir/joken_jwks#6]
I love that you guys have put the time and effort in to make this easy.

In the case someone has many jwks URL's (many integrations vs one), will it be safe for ets table and supervised task to have the jwks URL be dynamic like:

```
def init_opts(opts) do
  url = one_of_many_jwks_urls
  Keyword.merge(opts, jwks_url: url)
end
```

If so, it may be worth mentioning in docs that this can be done since it would be common to re-use an integration strategy with others.

**Comment by victorolinasc** [comment]
Hi @jrissler ! Sorry for the delay.

It probably will not work with many JWKS URLs. This is not a use case I was aware of when building it. 

Can you show me a good example where this is the case?

This is prepared for many public keys on the same jwks url though. If a token comes in we check for the kid header parameter. Does that help on your use case?

Thanks for the feedback!

**Comment by jrissler** [comment]
@victorolinasc Thanks, that does make sense.

What I was asking is: if you have multiple integrations each with a different single JWKS url, will the ets table support that? (say Google JWKS URL for one integration and another integration with a Azure JWKS URL, etc)

**Comment by victorolinasc** [comment]
Aaa I see your question now... let's break it into some parts so that I can properly answer it.

First, `JokenJwks` is a very simple hook implementation that intercepts the `before_verify` callback that checks for a header claim "kid" and then delegates the decision of finding a `Joken.Signer` to a "strategy". So, you could use your own strategy here and then you would be responsible for your storage strategy.

But it also comes with a built-in strategy that fetches keys and cache them on an ETS table. This ETS table is namespaced to the module defining the strategy. It is a dynamically defined module. So, when you do something like:

```elixir
defmodule MyApp.MyJwksStrategy do
  use JokenJwks.DefaultMatchStrategy
  # other options here
end
```

You automatically have a module named `MyApp.MyJwksStrategy.EtsCache`. There is defined an ETS table with that module name.

To use several providers with the built-in strategy, all you have to do is to use different modules like:

```elixir
defmodule MyApp.MyStrategy1 do
 use JokenJwks.DefaultMatchStrategy
  # URL 1
end

defmodule MyApp.MyStrategy2 do
  # URL 2
end
```

And, of course, use only one of them per token configuration. With that each of them will use different ETS table for holding keys :)

Tell me if that helps you out on this :)

**Comment by jrissler** [comment]
Ah perfect explanation- makes total sense! I suspected this was the case after reading through the code, but wanted to be sure :) thanks for reply and thanks for your work on this, def made my life easier :)
